apiVersion: batch/v1
kind: Job
metadata:
  name: migration-auth-db
spec:
  template:
    spec:
      containers:
        - name: migration-auth-db
          image: illiakniaziev/migration-auth-db
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secret
          env:
            - name: DATABASE_URL
              value: "$(DB_DIALECT)://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          command: ['npx', 'prisma', 'migrate', 'deploy']
      restartPolicy: Never
  backoffLimit: 5