replicaCount: 1

image:
  name: erbidium/pethome-client
  containerName: pethome-client
  port: 80
  tag: latest

service:
  ports:
    - name: http
      port: 80
      containerPort: 80

ingress:
  fullname: pethome-client 
  path: /
  port: http
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 512m