replicaCount: 1

image:
  name: erbidium/advert-service
  containerName: advert-service
  port: 8080
  tag: latest

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/adverts
  port: http

mssql-latest:
  mssqlPassword: "Qwerty123!"
  nameOverride: "advert-db"
  fullnameOverride: "advert-db"

fullnameOverride: "advert-service"