apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-db
  template:
    metadata:
      labels:
        app: auth-service-db
    spec:
      containers:
        - name: auth-service-db
          image: postgres:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: auth-db-config
            - secretRef:
                name: auth-db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-db-volume
      volumes:
        - name: auth-db-volume
          persistentVolumeClaim:
            claimName: auth-db-volume-claim