apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-db
  template:
    metadata:
      labels:
        app: user-service-db
    spec:
      containers:
        - name: user-service-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          envFrom:
            - configMapRef:
                name: user-service-db-config
            - secretRef:
                name: user-service-db-secret
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: sqldata-storage
      volumes:
      - name: sqldata-storage
        persistentVolumeClaim:
          claimName: user-service-db-claim
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    app: mssql-db
spec:
  ports:
    - port: 1433
  selector:
    app: user-service-db