apiVersion: batch/v1
kind: Job
metadata:
  name: migration-auth-db
spec:
  template:
    spec:
      containers:
        - name: migration-auth-db
          image: illiakniaziev/migration-auth-db
          imagePullPolicy: Always
          command: [ 'npx', 'prisma', 'migrate', 'deploy' ]
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secret
          env:
            - name: DATABASE_URL
              value: "postgresql://authdb:postgres@auth-db:5432/authdb"
      restartPolicy: Never
  backoffLimit: 10