apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: client               # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       app: client             # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: erbidium/pethome-client    # образ Docker
          imagePullPolicy: Always
          name: client           # ім'я контейнеру
          ports:
            - containerPort: 80  # порт по якому можна звертатись до поди