name: Docker images
on:
  push:
    branches: [ master ]
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push UserService docker image
        uses: docker/build-push-action@v3
        with:
          context: ./UserService
          file: ./UserService/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
          push: true

      - name: Build and push AdvertService docker image
        uses: docker/build-push-action@v3
        with:
          context: ./AdvertService
          file: ./AdvertService/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/advert-service:latest
          push: true

      - name: Build and push RequestService docker image
        uses: docker/build-push-action@v3
        with:
          context: ./RequestService
          file: ./RequestService/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/request-service:latest
          push: true

      - name: Build and push client docker image
        uses: docker/build-push-action@v3
        with:
          context: ./pethome-client
          file: ./pethome-client/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pethome-client:latest
          push: true